version: '3.8'

services:
  devvault-db:
    image: mysql:8.0
    container_name: devvault_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: devvault_db
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpassword
    ports:
      # HOST:CONTAINER
      # Mapping machine's 3307 to the container's 3306
      - '3307:3306'
    volumes:
      - db_data:/var/lib/mysql

    # The Database Visualizer
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  db_data: